apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-ticker.fullname" . }}-secret
type: Opaque
data:
{{- range $k, $v := .Values.deployment.secret }}
  {{ $k | quote | upper }}: {{ $v | b64enc | quote -}}
{{ end }}
