apiVersion: v2
name: stock-ticker
description: A Helm chart for the Stock Ticker service

type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: ingress-nginx
    version: 4.1.x
    repository: https://kubernetes.github.io/ingress-nginx
    condition: .Values.local.ingress.deploy
