replicaCount: 1

image:
  repository: docker.io/wpoch/stock-ticker
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   runAsNonRoot: true
   runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "false"
  hosts:
    - host: stock-ticker.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

deployment:
  env:
    SYMBOL: MSFT
    NDAYS: 7
  secret:
    APIKEY: # Get one from https://www.alphavantage.co/support/#api-key

local:
  ingress:
    deploy: false
